# Generated by Django 4.2.10 on 2024-03-09 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='email_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='open_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
