# Generated by Django 4.2.10 on 2024-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0004_usermodel_delete_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='counter_is',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
