# Generated by Django 4.2.10 on 2024-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0006_emailtracker_emailtracking_delete_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtracking',
            name='opened_at',
        ),
        migrations.AlterField(
            model_name='emailtracker',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
