# Generated by Django 4.2.10 on 2024-03-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0007_remove_emailtracking_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailtracker',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
