# Generated by Django 4.2.10 on 2024-03-20 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0010_delete_emailtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracker',
            name='email_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
