# Generated by Django 4.2.10 on 2024-03-22 12:04

import controllerEmail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0012_emailtracker_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtracker',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=controllerEmail.models.document_upload_path),
        ),
    ]
