# Generated by Django 4.2.10 on 2024-03-26 11:48

import controllerEmail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0013_alter_emailtracker_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=controllerEmail.models.image_upload_path),
        ),
    ]
