# Generated by Django 4.2.10 on 2024-03-27 00:33

import controllerEmail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0016_remove_emailtracker_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=controllerEmail.models.document_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=controllerEmail.models.image_upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailtracker',
            name='document',
        ),
        migrations.RemoveField(
            model_name='emailtracker',
            name='image',
        ),
        migrations.AddField(
            model_name='emailtracker',
            name='document',
            field=models.ManyToManyField(blank=True, to='controllerEmail.document'),
        ),
        migrations.AddField(
            model_name='emailtracker',
            name='image',
            field=models.ManyToManyField(blank=True, to='controllerEmail.image'),
        ),
    ]
