# Generated by Django 4.2.10 on 2024-03-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0017_document_image_remove_emailtracker_document_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
