# Generated by Django 4.2.10 on 2024-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0018_rename_image_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.ManyToManyField(to='controllerEmail.lien')),
            ],
        ),
        migrations.AddField(
            model_name='emailtracker',
            name='lien',
            field=models.ManyToManyField(blank=True, to='controllerEmail.lien'),
        ),
    ]
