# Generated by Django 4.2.10 on 2024-03-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0019_lien_emailtracker_lien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lien',
            name='links',
        ),
        migrations.AddField(
            model_name='lien',
            name='links',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
