# Generated by Django 4.2.10 on 2024-03-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0020_remove_lien_links_lien_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtracker',
            name='lien',
        ),
        migrations.DeleteModel(
            name='Lien',
        ),
    ]
