# Generated by Django 4.2.10 on 2024-03-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerEmail', '0021_remove_emailtracker_lien_delete_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracker',
            name='opened_at_link',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='opened_at_link',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
